name: django ERP
tagline: free your business
baseurl: /website
permalink: /blog/:year/:month/:day/:title
blog-url: /blog
project-url: https://github.com/django-erp/django-erp
project-download-url: https://github.com/django-erp/django-erp
wiki-url: https://github.com/django-erp/django-erp/wiki
markdown: redcarpet
highlighter: pygments
